// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {core} from '../models';

export function Base64Decode(arg1:string):Promise<string>;

export function Base64Encode(arg1:string):Promise<string>;

export function DirectLoading():Promise<core.Message>;

export function FileDelete(arg1:string):Promise<core.Message>;

export function FileImport():Promise<core.Message>;

export function FileOpen():Promise<core.Message>;

export function FileSave(arg1:string,arg2:string,arg3:boolean):Promise<core.Message>;

export function Fr(arg1:string):Promise<string>;

export function GetConfig(arg1:string,arg2:string):Promise<core.Message>;

export function GetImageData(arg1:string):Promise<core.Message>;

export function GetStaticResources():Promise<core.Message>;

export function ImageDownload(arg1:string):Promise<core.Message>;

export function ImageUpload():Promise<core.ImageFIle>;

export function LoadImage(arg1:string):Promise<core.Message>;

export function OpenImage():Promise<core.Message>;

export function SetConfig(arg1:string,arg2:string,arg3:string):Promise<core.Message>;

export function Trace(arg1:string,arg2:string):Promise<void>;
