// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Base64Decode(arg1) {
  return window['go']['core']['App']['Base64Decode'](arg1);
}

export function Base64Encode(arg1) {
  return window['go']['core']['App']['Base64Encode'](arg1);
}

export function DirectLoading() {
  return window['go']['core']['App']['DirectLoading']();
}

export function FileDelete(arg1) {
  return window['go']['core']['App']['FileDelete'](arg1);
}

export function FileOpen() {
  return window['go']['core']['App']['FileOpen']();
}

export function FileSave(arg1, arg2, arg3) {
  return window['go']['core']['App']['FileSave'](arg1, arg2, arg3);
}

export function Fr(arg1) {
  return window['go']['core']['App']['Fr'](arg1);
}

export function GetConfig(arg1, arg2) {
  return window['go']['core']['App']['GetConfig'](arg1, arg2);
}

export function GetImageData(arg1) {
  return window['go']['core']['App']['GetImageData'](arg1);
}

export function GetStaticResources() {
  return window['go']['core']['App']['GetStaticResources']();
}

export function GetVersion() {
  return window['go']['core']['App']['GetVersion']();
}

export function ImageDownload(arg1) {
  return window['go']['core']['App']['ImageDownload'](arg1);
}

export function ImageUpload() {
  return window['go']['core']['App']['ImageUpload']();
}

export function LoadImage(arg1) {
  return window['go']['core']['App']['LoadImage'](arg1);
}

export function NewFile() {
  return window['go']['core']['App']['NewFile']();
}

export function OpenImage() {
  return window['go']['core']['App']['OpenImage']();
}

export function SetConfig(arg1, arg2, arg3) {
  return window['go']['core']['App']['SetConfig'](arg1, arg2, arg3);
}

export function Trace(arg1, arg2) {
  return window['go']['core']['App']['Trace'](arg1, arg2);
}
