appearance:
  defaultOpen: maximised
  width: 1024
  height: 768
window:
  GPUAccelerate: true
  webviewUserData: ""
linux:
  windowTransparent: false
  GPUStrategy: always
staticResource:
  port: "7288"
  allowExt:
  - .jpg
  - .jpeg
  - .png
  - .gif
  - .bmp
  deleteCache: true
log:
  enable: true
  level: 4
  expired: 7
download:
  timeout: 10
core:
  maxTask: 5
  timeout: 300
  autoSave: true
  autoSaveInterval: 60
