version: 1.0.0.20241215_beta
buildTime: 2024/12/15
commit: 12efa4c8b95ef4b1926d60a4489b381e3a94ecbc
appearance:
  defaultOpen: maximised
  width: 1024
  height: 768
window:
  GPUAccelerate: false
  webviewUserData: ""
linux:
  windowTransparent: false
  GPUStrategy: always
staticResource:
  port: "7288"
  allowExt:
  - .jpg
  - .jpeg
  - .png
  - .gif
  - .svg
  deleteCache: true
log:
  enable: true
  level: 4
  expired: 7
download:
  timeout: 10
core:
  maxTask: 5
  timeout: 120
  autoSave: false
  autoSaveInterval: 30
epubSaving:
  textDir: auto
  layout: pre-paginated
  flow: auto
  spread: auto
  orientation: auto
  proportions: width=1200, height=600
