version: 1.1.0.20250407
buildTime: 2025/04/07
commit: c3b54d56820b9e1835e9a4ee02227e1d3823b7da
appearance:
  defaultOpen: maximised
  width: 1024
  height: 768
window:
  GPUAccelerate: false
  webviewUserData: ""
linux:
  windowTransparent: false
  GPUStrategy: always
staticResource:
  port: "7288"
  allowExt:
  - .jpg
  - .jpeg
  - .png
  - .gif
  - .svg
  deleteCache: true
log:
  enable: true
  level: 4
  expired: 7
download:
  timeout: 10
core:
  maxTask: 5
  timeout: 120
  autoSave: false
  autoSaveInterval: 30
epubSaving:
  textDir: auto
  layout: reflowable
  flow: auto
  spread: auto
  orientation: auto
  proportions: width=1200, height=600
