version: 1.0.0.20241227_beta
buildTime: 2024/12/27
commit: 6d30a331c3d9afcddfc56988606e0d805775e477
appearance:
  defaultOpen: maximised
  width: 1024
  height: 768
window:
  GPUAccelerate: false
  webviewUserData: ""
linux:
  windowTransparent: false
  GPUStrategy: always
staticResource:
  port: "7288"
  allowExt:
  - .jpg
  - .jpeg
  - .png
  - .gif
  - .svg
  deleteCache: true
log:
  enable: true
  level: 4
  expired: 7
download:
  timeout: 10
core:
  maxTask: 5
  timeout: 120
  autoSave: false
  autoSaveInterval: 30
epubSaving:
  textDir: auto
  layout: reflowable
  flow: auto
  spread: auto
  orientation: auto
  proportions: width=1200, height=600
