// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Base64Decode(arg1) {
  return window['go']['main']['App']['Base64Decode'](arg1);
}

export function Base64Encode(arg1) {
  return window['go']['main']['App']['Base64Encode'](arg1);
}

export function DirectLoading() {
  return window['go']['main']['App']['DirectLoading']();
}

export function FileDelete(arg1) {
  return window['go']['main']['App']['FileDelete'](arg1);
}

export function FileOpen() {
  return window['go']['main']['App']['FileOpen']();
}

export function FileSave(arg1, arg2, arg3) {
  return window['go']['main']['App']['FileSave'](arg1, arg2, arg3);
}

export function Fr(arg1) {
  return window['go']['main']['App']['Fr'](arg1);
}

export function GetConfig(arg1, arg2) {
  return window['go']['main']['App']['GetConfig'](arg1, arg2);
}

export function GetImageData(arg1) {
  return window['go']['main']['App']['GetImageData'](arg1);
}

export function GetStaticResources() {
  return window['go']['main']['App']['GetStaticResources']();
}

export function ImageUpload() {
  return window['go']['main']['App']['ImageUpload']();
}

export function OpenImage() {
  return window['go']['main']['App']['OpenImage']();
}

export function Publish(arg1, arg2) {
  return window['go']['main']['App']['Publish'](arg1, arg2);
}

export function SaveConfig() {
  return window['go']['main']['App']['SaveConfig']();
}

export function SetConfig(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetConfig'](arg1, arg2, arg3);
}
