// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function DirectLoading():Promise<main.Message>;

export function FileDelete(arg1:string):Promise<main.Message>;

export function FileOpen():Promise<string>;

export function FileSave(arg1:string,arg2:string):Promise<main.Message>;

export function Fr(arg1:string):Promise<string>;

export function GetImageData(arg1:string):Promise<main.Message>;

export function GetStaticResources():Promise<string>;

export function ImageUpload():Promise<main.ImageFIle>;

export function OpenImage():Promise<main.Message>;

export function Publish(arg1:string,arg2:string):Promise<main.Message>;
